### ISSUE TITLE
[BUG](arborist) unnecessary ERESOLVE warnings

### ISSUE THREAD

**Issue by lukekarrys** [npm/cli#4270]
# What / Why
The following tree can be built without any conflicting peerDependencies, but it still displays a warning.

```
// overlapping peerSet
project -> (a@1)
a@1 -> (b), PEER(c@1||2), PEER(d@1||2)
b -> PEER(c@1), PEER(d@1)
c -> ()
d@1 -> PEER(c@1)
d@2 -> PEER(c@2)
```

## Where
This is a regression from `2.8.3` to `2.8.4` so I suspect it has to do with https://github.com/npm/arborist/blob/f498f2a7223d6b02b3791a5bc25d4eca82ebb3d0/lib/place-dep.js#L419 which warns earlier than we did previously.

### Steps to Reproduce
```
arborist reify --add="@lukekarrys/workspace-peer-dep-infinite-loop-a@1"
```
<details><summary>Produces the following warning</summary>
<p>

```
5868 warn ERESOLVE overriding peer dependency {
5868 warn   code: 'ERESOLVE',
5868 warn   edge: {
5868 warn     type: 'peer',
5868 warn     name: '@lukekarrys/workspace-peer-dep-infinite-loop-c',
5868 warn     spec: '2.0.0',
5868 warn     from: {
5868 warn       name: '@lukekarrys/workspace-peer-dep-infinite-loop-d',
5868 warn       version: '2.0.0',
5868 warn       location: 'node_modules/@lukekarrys/workspace-peer-dep-infinite-loop-d',
5868 warn       isWorkspace: false,
5868 warn       dependents: [
5868 warn         {
5868 warn           type: 'peer',
5868 warn           name: '@lukekarrys/workspace-peer-dep-infinite-loop-d',
5868 warn           spec: '1.0.0 || 2.0.0',
5868 warn           from: {
5868 warn             name: '@lukekarrys/workspace-peer-dep-infinite-loop-a',
5868 warn             version: '1.0.0',
5868 warn             location: 'node_modules/@lukekarrys/workspace-peer-dep-infinite-loop-a',
5868 warn             isWorkspace: false,
5868 warn             dependents: [
5868 warn               {
5868 warn                 type: 'prod',
5868 warn                 name: '@lukekarrys/workspace-peer-dep-infinite-loop-a',
5868 warn                 spec: '1',
5868 warn                 from: {
5868 warn                   location: '/Users/lukekarrys/Desktop/arborist-tests/test-dir'
5868 warn                 }
5868 warn               }
5868 warn             ]
5868 warn           }
5868 warn         }
5868 warn       ]
5868 warn     }
5868 warn   },
5868 warn   dep: {
5868 warn     name: '@lukekarrys/workspace-peer-dep-infinite-loop-c',
5868 warn     version: '1.0.0',
5868 warn     whileInstalling: {
5868 warn       name: '@lukekarrys/workspace-peer-dep-infinite-loop-a',
5868 warn       version: '1.0.0',
5868 warn       path: '/Users/lukekarrys/Desktop/arborist-tests/test-dir/node_modules/@lukekarrys/workspace-peer-dep-infinite-loop-a'
5868 warn     },
5868 warn     location: 'node_modules/@lukekarrys/workspace-peer-dep-infinite-loop-c',
5868 warn     isWorkspace: false,
5868 warn     dependents: [
5868 warn       {
5868 warn         type: 'peer',
5868 warn         name: '@lukekarrys/workspace-peer-dep-infinite-loop-c',
5868 warn         spec: '2.0.0',
5868 warn         from: {
5868 warn           name: '@lukekarrys/workspace-peer-dep-infinite-loop-d',
5868 warn           version: '2.0.0',
5868 warn           location: 'node_modules/@lukekarrys/workspace-peer-dep-infinite-loop-d',
5868 warn           isWorkspace: false,
5868 warn           dependents: [
5868 warn             {
5868 warn               type: 'peer',
5868 warn               name: '@lukekarrys/workspace-peer-dep-infinite-loop-d',
5868 warn               spec: '1.0.0 || 2.0.0',
5868 warn               from: {
5868 warn                 name: '@lukekarrys/workspace-peer-dep-infinite-loop-a',
5868 warn                 version: '1.0.0',
5868 warn                 location: 'node_modules/@lukekarrys/workspace-peer-dep-infinite-loop-a',
5868 warn                 isWorkspace: false,
5868 warn                 dependents: [
5868 warn                   {
5868 warn                     type: 'prod',
5868 warn                     name: '@lukekarrys/workspace-peer-dep-infinite-loop-a',
5868 warn                     spec: '1',
5868 warn                     from: {
5868 warn                       location: '/Users/lukekarrys/Desktop/arborist-tests/test-dir'
5868 warn                     }
5868 warn                   }
5868 warn                 ]
5868 warn               }
5868 warn             }
5868 warn           ]
5868 warn         }
5868 warn       }
5868 warn     ]
5868 warn   },
5868 warn   current: {
5868 warn     name: '@lukekarrys/workspace-peer-dep-infinite-loop-c',
5868 warn     version: '2.0.0',
5868 warn     location: 'node_modules/@lukekarrys/workspace-peer-dep-infinite-loop-c',
5868 warn     isWorkspace: false,
5868 warn     dependents: [
5868 warn       {
5868 warn         type: 'peer',
5868 warn         name: '@lukekarrys/workspace-peer-dep-infinite-loop-c',
5868 warn         spec: '2.0.0',
5868 warn         from: {
5868 warn           name: '@lukekarrys/workspace-peer-dep-infinite-loop-d',
5868 warn           version: '2.0.0',
5868 warn           location: 'node_modules/@lukekarrys/workspace-peer-dep-infinite-loop-d',
5868 warn           isWorkspace: false,
5868 warn           dependents: [
5868 warn             {
5868 warn               type: 'peer',
5868 warn               name: '@lukekarrys/workspace-peer-dep-infinite-loop-d',
5868 warn               spec: '1.0.0 || 2.0.0',
5868 warn               from: {
5868 warn                 name: '@lukekarrys/workspace-peer-dep-infinite-loop-a',
5868 warn                 version: '1.0.0',
5868 warn                 location: 'node_modules/@lukekarrys/workspace-peer-dep-infinite-loop-a',
5868 warn                 isWorkspace: false,
5868 warn                 dependents: [
5868 warn                   {
5868 warn                     type: 'prod',
5868 warn                     name: '@lukekarrys/workspace-peer-dep-infinite-loop-a',
5868 warn                     spec: '1',
5868 warn                     from: {
5868 warn                       location: '/Users/lukekarrys/Desktop/arborist-tests/test-dir'
5868 warn                     }
5868 warn                   }
5868 warn                 ]
5868 warn               }
5868 warn             }
5868 warn           ]
5868 warn         }
5868 warn       }
5868 warn     ]
5868 warn   },
5868 warn   peerConflict: {
5868 warn     name: '@lukekarrys/workspace-peer-dep-infinite-loop-c',
5868 warn     version: '2.0.0',
5868 warn     location: 'node_modules/@lukekarrys/workspace-peer-dep-infinite-loop-c',
5868 warn     isWorkspace: false,
5868 warn     dependents: [
5868 warn       {
5868 warn         type: 'peer',
5868 warn         name: '@lukekarrys/workspace-peer-dep-infinite-loop-c',
5868 warn         spec: '2.0.0',
5868 warn         from: {
5868 warn           name: '@lukekarrys/workspace-peer-dep-infinite-loop-d',
5868 warn           version: '2.0.0',
5868 warn           location: 'node_modules/@lukekarrys/workspace-peer-dep-infinite-loop-d',
5868 warn           isWorkspace: false,
5868 warn           dependents: [
5868 warn             {
5868 warn               type: 'peer',
5868 warn               name: '@lukekarrys/workspace-peer-dep-infinite-loop-d',
5868 warn               spec: '1.0.0 || 2.0.0',
5868 warn               from: {
5868 warn                 name: '@lukekarrys/workspace-peer-dep-infinite-loop-a',
5868 warn                 version: '1.0.0',
5868 warn                 location: 'node_modules/@lukekarrys/workspace-peer-dep-infinite-loop-a',
5868 warn                 isWorkspace: false,
5868 warn                 dependents: [
5868 warn                   {
5868 warn                     type: 'prod',
5868 warn                     name: '@lukekarrys/workspace-peer-dep-infinite-loop-a',
5868 warn                     spec: '1',
5868 warn                     from: {
5868 warn                       location: '/Users/lukekarrys/Desktop/arborist-tests/test-dir'
5868 warn                     }
5868 warn                   }
5868 warn                 ]
5868 warn               }
5868 warn             }
5868 warn           ]
5868 warn         }
5868 warn       }
5868 warn     ]
5868 warn   },
5868 warn   strictPeerDeps: false,
5868 warn   force: false,
5868 warn   isMine: false
5868 warn }
```

</p>
</details> 

### Expected Behavior
It should not warn

## References
https://github.com/npm/arborist/pull/343

## TODOs

Since this is a regression from npm/arborist#326, I went to the snapshots and found the following places where there were warnings were introduced when placing deps. These should be checked also to see if they should be fixed as well.

- [ ] [`test/place-dep.js TAP placement tests prod dep directly on conflicted peer, newer, force > warnings 1`](https://github.com/npm/arborist/commit/cb623a27fd327b63cd21a4cf96f892d39d1dd308#diff-e68bb1c8f7773a0dc0af8a23874f57d40e04ef0bf11585f9d139efc3c5211413L6237)
- [ ] [`test/place-dep.js TAP placement tests prod dep directly on conflicted peer, older, force > warnings 1`](https://github.com/npm/arborist/commit/cb623a27fd327b63cd21a4cf96f892d39d1dd308#diff-e68bb1c8f7773a0dc0af8a23874f57d40e04ef0bf11585f9d139efc3c5211413L6836)
- [ ] [`test/place-dep.js TAP placement tests replacing existing peer set > warnings 1`](https://github.com/npm/arborist/commit/cb623a27fd327b63cd21a4cf96f892d39d1dd308#diff-e68bb1c8f7773a0dc0af8a23874f57d40e04ef0bf11585f9d139efc3c5211413L7459)
- [ ] [`test/place-dep.js TAP placement tests replacing overlapping peer sets > warnings 1`](https://github.com/npm/arborist/commit/cb623a27fd327b63cd21a4cf96f892d39d1dd308#diff-e68bb1c8f7773a0dc0af8a23874f57d40e04ef0bf11585f9d139efc3c5211413L7743)
- [ ] [`test/place-dep.js TAP placement tests replacing partially overlapping peer sets, superset > warnings 1`](https://github.com/npm/arborist/commit/cb623a27fd327b63cd21a4cf96f892d39d1dd308#diff-e68bb1c8f7773a0dc0af8a23874f57d40e04ef0bf11585f9d139efc3c5211413L8391)
