### ISSUE TITLE
> https://git-scm.com/download/linux

### ISSUE THREAD

**Issue by RHYTHMSOUND** [npm/cli#6579]
![archive_illustration-1.png](https://github.com/npm/cli/assets/136238448/026f40bb-91c8-4cb3-9683-55d229ca120a)
``` 
# cd /home/user/my_project
```
![active_connections (1).png](https://github.com/npm/cli/assets/136238448/4a970645-ddf4-4998-b330-104b16b3b1b4)
`http://localhost:8158/progit.html`

>
![wp-1686984708617-1](https://github.com/ORG-YORK/ANDROID-ENCODING/assets/90439668/374b8e0b-d9db-4973-af57-4e5a040a2ef5)

```[tasklist]
### Tasks
- [x] cd /home/user/my_projectcontent://com.android.providers
- [x] content://com.android.providers.downloads.documents/document/msf%3A1000065076cd /home/user/my_projectcontent://com.android.providers
- [ ] https://github.com/npm/cli/issues/6580
- [ ] https://github.com/npm/cli/issues/6583
- [ ] https://github.com/npm/cli/issues/6584
- [ ] https://github.com/npm/cli/issues/6581
- [ ] https://github.com/npm/cli/issues/6400
- [ ] https://github.com/npm/cli/issues/6582
- [ ] https://github.com/npm/cli/issues/6588
- [ ] https://github.com/npm/cli/issues/6589
```

**Comment by RHYTHMSOUND** [comment]
> ![archive_illustration-1.png](https://github.com/npm/cli/assets/136238448/026f40bb-91c8-4cb3-9683-55d229ca120a)
> ``` 
> # cd /home/user/my_project
> ```
> ![active_connections (1).png](https://github.com/npm/cli/assets/136238448/4a970645-ddf4-4998-b330-104b16b3b1b4)
> `http://localhost:8158/progit.html`
> 
> > ![screenshot.png](https://github.com/npm/cli/assets/136238448/6ed2a59d-4313-4d0a-94d1-ec4ada860de9)
> 
> 
> 

![readme.txt](https://github.com/npm/cli/files/11815410/readme.txt)

**Comment by RHYTHMSOUND** [comment]
![3b9e2a40-d870-4f15-bf24-679c320dd1fd](https://github.com/npm/cli/assets/136238448/f4178e56-8e5b-4f66-b7fe-392548689717)
# Docker Desktop en Linux 
 > [https://github.com/opencontainers/image-spec/blob/v1.0.0/image-index.md](https://hub.docker.com/u/library)
evernote:///view/241869088/s570/47d18824-d3d2-0f0b-bcbe-117effd2ba50/b518b491-df94-dc57-279c-a7b4af471ab9 evernote:///view/241869088/s570/14b49634-c62a-f906-ee73-2b3a421ab76e/b518b491-df94-dc57-279c-a7b4af471ab9evernote:///view/241869088/s570/00325fa9-6bad-963a-73ac-f9e92da6b98e/b518b491-df94-dc57-279c-a7b4af471ab9evernote:///view/241869088/s570/2cdbde35-b098-2fda-9e51-18ee7ae6aa78/b518b491-df94-dc57-279c-a7b4af471ab9evernote:///view/241869088/s570/bbcf7d21-dcc9-8076-3ad3-37c715385ebe/b518b491-df94-dc57-279c-a7b4af471ab9 [README](https://github.com/docker-library/bashbrew#readme) for more information. 
![descarga (1)](https://github.com/npm/cli/assets/136238448/f6a00c6f-fab5-4a41-8ad1-e3eb8c689b8d)
![descarga (2)](https://github.com/npm/cli/assets/136238448/45546473-96bb-4245-9d6b-fcb11095e5cc)
![descarga (3)](https://github.com/npm/cli/assets/136238448/c2673397-27a8-408d-bc07-de8289b3ba9b)
![descarga (6)](https://github.com/npm/cli/assets/136238448/2bc1d282-9f52-4d02-baee-ab5025d78c46)
