### ISSUE TITLE
[BUG] NPM Install is slow on local network but works fine with my mobile carrier network.

### ISSUE THREAD

**Issue by aslaii** [npm/cli#6681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest npm version

- [X] I am using the latest npm

### Current Behavior

`npm install` takes minutes to complete.

### Expected Behavior

`npm install` should takes seconds.

### Steps To Reproduce

1. npm install packages
2. wait
3. either ETIMEDOUT or will install

### Environment

- npm: 9.8.1
- Node.js: 18.16.1
- OS Name: Windows 11 Preview
- System Model Name: Desktop PC
- npm config:
```ini
; "builtin" config from C:\Users\user\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\user\\AppData\\Roaming\\npm"

; "global" config from C:\Users\user\AppData\Roaming\npm\etc\npmrc

; registry = "http://registry.npmjs.org/" ; overridden by user

; "user" config from C:\Users\user\.npmrc

progress = false
registry = "http://registry.npmjs.org/"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v18.16.1
; npm local prefix = C:\Users\user
; npm version = 9.8.1
; cwd = C:\Users\user
; HOME = C:\Users\user
; Run `npm config ls -l` to show all defaults.

```

I have tried both pnpm and yarn along with other solutions I found on the internet. The issue appears to be with my network. Visiting the website: registry.npmjs.org presents no problems.

Please have a look at this image:
![wzUe2eA97h](https://github.com/npm/cli/assets/111640116/ff60b626-0f75-443d-90d9-7e1075c8245a)

The red box indicates that the computer is connected via Ethernet or Wifi on my home network. The green box shows that the computer is connected via a Mobile Hotspot on my mobile data carrier network.

As you can see, even though I am using pnpm on the first install, it produces an ETIMEDOUT error. However, once I connect my PC with my mobile hotspot, everything works fine and installation is completed in just 7 seconds.

This issue appears to be with my local network. I will undertake a full network overhaul on my end. I am just posting this to see if I can find a solution to the problem.

```[tasklist]
### Tasks
- [x] Network Overhaul
- [ ] Reset Network Settings
- [ ] Try Linux
- [ ] Reset PC
```

**Comment by aslaii** [comment]
After overhauling the network, the issue seems to have improved significantly. It has completely eliminated the ETIMEDOUT error, though it still requires more testing. For now, I will close this issue.

Here are the results:

![NVIDIA_Share_WXOhkReMED](https://github.com/npm/cli/assets/111640116/ea3eaf9f-6d86-42ad-88de-968346aa5b30)

The first npm install was completed in under 31 minutes. After that, I removed the node_modules folder and installed them again. This time, it installed in just 5 seconds.

![NVIDIA_Share_giftF0FErG](https://github.com/npm/cli/assets/111640116/5534eef0-ea2a-4b14-81df-fe93f3c38777)

Then, I initialized another test project using `npm create vite` to test if I would still encounter the error. The NPM response seems promising compared to before, when it would take a while to get to the vite setup.

![NVIDIA_Share_i9zdGWZAtc](https://github.com/npm/cli/assets/111640116/f62bb4e7-847e-49f1-99c3-e4e297b96baf)

Performing `npm install` now does not produce any ETIMEDOUT error, and it completes in under 17 minutes, which is still slow. However, at least the error is gone.

The network overhaul included:
1. Resetting every router
2. Re-seating network cables
3. General cleaning
