### ISSUE TITLE
Runtinme Error loading 

### ISSUE THREAD

**Issue by colleenpridemore** [npm/cli#7444]
decentralandfoundation.decentraland-sdk7

Installing extension v1.50.1...
Spawning child process "npm install" with pid=7316
npm ERR! Exit handler never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

```[tasklist]
### Tasks
- [ ] https://github.com/npm/cli/pull/7538
- [ ] https://github.com/npm/cli/pull/7539
- [ ] https://github.com/npm/cli/issues/5943
- [ ] https://github.com/npm/cli/issues/6097
- [ ] https://github.com/npm/cli/issues/6108
- [ ] https://github.com/npm/cli/issues/7530
- [ ] https://github.com/npm/cli/pull/7025
- [ ] https://github.com/npm/cli/issues/7537
- [ ] https://github.com/npm/cli/issues/7138
- [ ] https://github.com/npm/cli/issues/6407
- [ ] https://github.com/npm/cli/pull/7363
- [ ] https://github.com/npm/cli/pull/7508
- [ ] https://github.com/npm/cli/pull/7536
- [ ] https://github.com/npm/cli/issues/5444
- [ ] https://github.com/npm/cli/issues/5021
- [ ] https://github.com/npm/cli/issues/7114
- [ ] https://github.com/npm/cli/issues/5776
- [ ] https://github.com/npm/cli/issues/5870
- [ ] https://github.com/npm/cli/issues/3576
- [ ] https://github.com/npm/cli/pull/7460
- [ ] https://github.com/npm/cli/pull/7534
- [ ] https://github.com/npm/cli/pull/7228
- [ ] https://github.com/npm/cli/pull/7513
- [ ] https://github.com/npm/cli/pull/7533
- [ ] https://github.com/npm/cli/issues/7528
- [ ] https://github.com/npm/cli/issues/7529
- [ ] https://github.com/npm/cli/issues/7529
```
